### ISSUE TITLE
フルスクリーン対応

### ISSUE THREAD

**Issue by ikekou** [bassdrum-org/yashironi-pwa#2]
ホーム画面のアイコンから起動した場合にフルスクリーン表示できるはずなのでフルスクリーン表示にする

**Comment by zhaozzhang** [comment]
https://github.com/user-attachments/assets/012145e5-3849-4634-9157-ce25b71a2c8f

**Comment by ikekou** [comment]
![Image](https://github.com/user-attachments/assets/9f34bc0e-4d22-4217-82dc-a860a3884cc1)
上のここって消せないんでしたっけ？

**Comment by zhaozzhang** [comment]
@ikekou 
調べたところ、ステータスバーを完全に消すことができなくて、背景を透明にするだけができます
![Image](https://github.com/user-attachments/assets/bd4a6a93-1ea0-4053-9527-de266ade0b66)
参照リンク：
https://dev.to/oncode/display-your-pwa-website-fullscreen-4776
https://qiita.com/hatt_takumi/items/74d48a9430f2f826b1a3

**Comment by ikekou** [comment]
完全に消せないの了解です！
